service: automotores-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

layers:
  CommonDependenciesLambdaLayer:
    arn: arn:aws:lambda:us-east-1:768534398312:layer:automotores-dependencies:10
    compatibleRuntimes:
      - nodejs18.x

functions:
  app:
    handler: handler.app
    layers:
      - { Ref: CommonDependenciesLambdaLayer }
    events:
      - http:
          path: /{proxy+}
          method: any

package:
  exclude:
    - node_modules/**
    - package.json
    - package-lock.json
    - .git/**
    - .vscode/**
    - .serverless/**
